### PR TITLE
Tiny refresh of the Rails theme

### PR DESCRIPTION
**Pull request by robin850**
Hi,

I take the liberty to open a pull request to refresh a bit the style of the API site for Ruby on Rails. If you don't like something or have ideas, feel free to comment ! That'd be cool to use a more modern style for the site ; here's how it looks at the moment:

capture d ecran 2017-05-05 a 23 45 06

* [x] Improve a bit the banner color to be close to the new Ruby on Rails site.
* [x] Improve a bit the styling of the panel using vector images and increasing the size of items.
* [x] Improve a bit the styling of the search field (full credit to octicons for the search icon)
* [x] Increase the font size to make things more readable.
* [x] Remove the yellow style of the code blocks.
* [x] Fix the search results displaying.

cc @kaspth @fxn @zzak @vipulnsward @prathamesh-sonpatki @maclover7

Have a nice day ! :-)

### CODE REVIEW

**Comment by vipulnsward** [comment]
Sweet. I think there is also an issue discussing SEO of the doc site. 
Not sure if that go through with this.

**Comment by robin850** [comment]
Yes completely, I would love to have a look at this but for another PR. I guess we should try to get rid of the `iframe` thingy before. :-)

**Comment by kaspth** [comment]
Looks better 👍

Not sure if we should follow up the main Rails site redesign by going after the auxiliary sites like guides, contributors and api. Though that's for @dhh since he's the one with the designer access 😄

**Comment by dhh** [comment]
Can you post a screenshot of what it looks after these changes? Would be nice to start matching the look from the main homepage.

**Comment by kaspth** [comment]
@dhh there's a screenshot in the PR description.

**Comment by robin850** [comment]
Thanks for the feedback Kasper !

David, it is not really "transcendent" but it's a bit different. 😄 Here's a screenshot comparing the two versions:

comparison

The color used by the banner is a bit different from the one used by the logo which is `#CC0000` (<-- Damn, didn't know about this GH feature) because it feels a bit "harsh" for the eyes since the banner is bigger.

Feel free if you have any idea or don't like something ; this refresh isn't revolutionary at all but I can improve it if you have something in mind !

**Comment by dhh** [comment]
Ah, yeah, missed the changes first time around. All good by me.

**Comment by robin850** [comment]
If there is no objection, this can be shipped. :-)

**Pull request merged**
