### PR TITLE
Update Merge script to work with sdoc v2

### PR DESCRIPTION
**Pull request by mikdiet**
Hello, following up https://github.com/zzak/sdoc/issues/152, I fixed merge class.

https://user-images.githubusercontent.com/426230/116624449-978cd880-a950-11eb-9c72-3d40af176d4a.mov

Also could play live version at http://api.rusrails.ru

### CODE REVIEW

**Review by zzak — APPROVED** [review]
@mikdiet I've approved this on a code-change basis, but I wasn't able to verify the merge behavior. I was hoping to see it live on [our netlify](https://deploy-preview-167--nervous-roentgen-6c1877.netlify.app/) but I don't see it. Maybe I'm missing something?

**Comment by mikdiet** [comment]
@zzak netlify doesn't run merge script at all https://github.com/zzak/sdoc/blob/master/netlify.toml#L2

Unfortunately I'm not familiar with this tool. We may need another instance to run merge script separately.

**Comment by mikdiet** [comment]
I've figured out that I forgot to update readme "Contributing" section with how to generate merge docs for debugging purpose - I'll add it tomorrow.

**Comment by zzak** [comment]
> I've figured out that I forgot to update readme "Contributing" section with how to generate merge docs for debugging purpose - I'll add it tomorrow.

@mikdiet Please feel free to submit a new patch, I will merge this as is. Thanks for working on it!

**Pull request merged**
